SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRAN
UPDATE Application.People
SET PreferredName = 'Kaila'
WHERE PersonID = 2;

ROLLBACK TRAN

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRAN
UPDATE Application.People
SET PreferredName = 'Kayla'
WHERE PersonID = 3;

ROLLBACK TRAN


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRAN
UPDATE Application.People
SET PreferredName = 'Kaila'
WHERE PersonID = 2;

ROLLBACK TRAN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN
UPDATE Application.People
SET PreferredName = 'Kaila'
WHERE PreferredName = 'Kayla';

ROLLBACK TRAN
